name: Render Deploy

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # コードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Dockerイメージのビルド
      - name: Build Docker image
        run: |
          docker build -t inoue/my_flask_hp:latest .

      # Renderへのデプロイ
      - uses: ttskch/render-deploy@v1.0.0
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          interval: 20
          timeout: 300 
